### ISSUE TITLE
Can't run on iMac M1

### ISSUE THREAD

**Issue by ahmuu** [SamurAIGPT/privateGPT#13] opened 2023-05-27 22:51 UTC
I removed the `pywin32` module from the requirements, though I'm still getting errors when running `install -r requirements.txt`.  This is the one I'm getting 
```
ERROR: Could not find a version that satisfies the requirement putz-deprecation-shim==0.1.0.post0 (from versions: none) 
ERROR: No matching distribution found for putz-deprecation-shim==0.1.0.post0
```
---
And when running `privateGPT.py ` -- I'm getting the error below

```
File "/Users/XX/Desktop/privateGPT/server/privateGPT.py", line 1, in <module>
    from flask import Flask,jsonify, render_template, flash, redirect, url_for, Markup, request
ModuleNotFoundError: No module named 'flask'

(base) XX@XXXX-iMac server % python3 privateGPT.py           
Traceback (most recent call last):
  File "/Users/am/Desktop/privateGPT/server/privateGPT.py", line 1, in <module>
    from flask import Flask,jsonify, render_template, flash, redirect, url_for, Markup, request

ModuleNotFoundError: No module named 'flask'
```

Appreciate any support! :)

**Comment by nexuslux** [comment] 2023-05-28 12:57
I got past this part by just installing flask directly afterwards.

pip install flask

and then checking that flask is install.

flask --version

**Comment by joemccann** [comment] 2023-05-28 20:14
You can also comment out line 97 in `requirements.txt`

```sh
# pywin32==306
```

**Comment by Anil-matcha** [comment] 2023-05-28 20:52
@joemccann has added a fix now in https://github.com/SamurAIGPT/privateGPT/pull/17

**Comment by Anil-matcha** [comment] 2023-05-29 11:45
Closing as the issue is fixed

**Closed by Anil-matcha** 2023-05-29 11:45 UTC
